name: Docker

on: [push]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: quay.io
  USER_NAME: swoturkey
  # github.repository as <account>/<repo>
  IMAGE_NAME: swoturkey/ratings-web


jobs:
  deployToTest:
    #if: github.event_name != 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
     - uses: azure/k8s-set-context@v1
       with:
         method: service-account
         k8s-url: ${{secrets.K8S_URL}}
         k8s-secret: ${{ secrets.K8S_SECRET }}
       id: setcontext
     - name: get nodes
       run: kubectl get nodes   

      
 
  
      