name: Docker

on: [push]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: quay.io
  USER_NAME: swoturkey
  # github.repository as <account>/<repo>
  IMAGE_NAME: swoturkey/ratings-web


jobs:

  deployToTest:
    #if: github.event_name != 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
     - uses: azure/k8s-set-context@v1
       with:
        method: service-account
        cluster-type: 'arc'
        cluster-name: internal
        resource-group: springcloudrg
        token: '${{ secrets.SA_TOKEN }}'
       id: setcontext
       run: kubectl get nodes
       shell: bash

      
 
  
      