name: AKS Deployment Test

on: [pull_request]

jobs:
  Aks_Deployment_Job:
    runs-on: ubuntu-latest
    name: Testing Aks Deployment
    
    steps:
       
       
      - name: Checkout repositorys
        uses: actions/checkout@v2
    
       
      - id: AksDeploymentTest
        uses: enespekdas/composite-action-aksdeployment@v2.1
        with:
          REGISTRY: quay.io
          USER_NAME: swoturkey
          IMAGE_NAME: swoturkey/ratings-web
          K8S_URL: ${{ secrets.K8S_URL }} 
          K8S_SECRET: ${{ secrets.K8S_SECRET }}
      - run: echo  ${{ steps.AksDeploymentTest.outputs.Result }} 
        shell: bash
      - run: echo " Selam , bitti"
        shell: bash